// Plant database scoped to Houston / Gulf Coast Prairies (USDA zone 9b).
// plantMonths / bloomMonths use 1-12. plantMonths = when to put it in the
// ground here (natives establish best in fall; veggies follow the Harris
// County fall/spring garden calendar).
window.PLANTS = [
  // ---------- Native perennials ----------
  { id: 'turkscap', name: "Turk's Cap", botanical: 'Malvaviscus arboreus var. drummondii',
    type: 'perennial', native: true, sun: 'part shade', water: 'low',
    plantMonths: [9,10,11,12,1,2,3], bloomMonths: [5,6,7,8,9,10,11],
    establishDays: 60, heightFt: 4, spacingFt: 3, color: '#3e7a33', bloom: '#d63333',
    notes: 'Hummingbird magnet; thrives in the shade where lawns fail. Nearly indestructible in Houston clay.' },
  { id: 'gcmuhly', name: 'Gulf Coast Muhly', botanical: 'Muhlenbergia capillaris',
    type: 'grass', native: true, sun: 'full sun', water: 'low',
    plantMonths: [9,10,11,2,3,4], bloomMonths: [10,11],
    establishDays: 90, heightFt: 3, spacingFt: 3, color: '#7a9455', bloom: '#d98bb6',
    notes: 'Pink cloud of seed heads every October. Needs drainage — mound the bed in clay.' },
  { id: 'txlantana', name: 'Texas Lantana', botanical: 'Lantana urticoides',
    type: 'perennial', native: true, sun: 'full sun', water: 'low',
    plantMonths: [3,4,5,9,10], bloomMonths: [4,5,6,7,8,9,10],
    establishDays: 45, heightFt: 3, spacingFt: 4, color: '#4a7a2e', bloom: '#f2a13c',
    notes: 'Blooms through the worst of August with no help. Butterflies all season.' },
  { id: 'autumnsage', name: 'Autumn Sage', botanical: 'Salvia greggii',
    type: 'perennial', native: true, sun: 'full sun', water: 'low',
    plantMonths: [9,10,11,2,3], bloomMonths: [3,4,5,6,9,10,11],
    establishDays: 45, heightFt: 2, spacingFt: 2, color: '#5b7d4a', bloom: '#e0426a',
    notes: 'Hummingbirds; hates wet feet — raised bed or slope in this soil.' },
  { id: 'scarletsage', name: 'Scarlet Sage', botanical: 'Salvia coccinea',
    type: 'perennial', native: true, sun: 'part shade', water: 'medium',
    plantMonths: [3,4,9,10], bloomMonths: [3,4,5,6,7,8,9,10,11],
    establishDays: 30, heightFt: 2, spacingFt: 1, color: '#4c8040', bloom: '#e63b2e',
    notes: 'Reseeds itself politely; blooms almost year-round in 9b.' },
  { id: 'mistflower', name: "Gregg's Mistflower", botanical: 'Conoclinium greggii',
    type: 'perennial', native: true, sun: 'part shade', water: 'medium',
    plantMonths: [9,10,3,4], bloomMonths: [6,7,8,9,10,11],
    establishDays: 45, heightFt: 1.5, spacingFt: 2, color: '#57804d', bloom: '#9fa8e8',
    notes: 'THE queen-butterfly plant in fall. Spreads to fill a bed.' },
  { id: 'flameacanthus', name: 'Flame Acanthus', botanical: 'Anisacanthus quadrifidus var. wrightii',
    type: 'shrub', native: true, sun: 'full sun', water: 'low',
    plantMonths: [9,10,11,3], bloomMonths: [6,7,8,9,10],
    establishDays: 60, heightFt: 4, spacingFt: 3, color: '#6d8a4b', bloom: '#f06a2a',
    notes: 'Hummingbird shrub that laughs at drought and reflected heat.' },
  { id: 'blackeyedsusan', name: 'Black-eyed Susan', botanical: 'Rudbeckia hirta',
    type: 'perennial', native: true, sun: 'full sun', water: 'medium',
    plantMonths: [3,4,10,11], bloomMonths: [5,6,7,8,9],
    establishDays: 30, heightFt: 2, spacingFt: 1, color: '#567c34', bloom: '#f2b21e',
    notes: 'Sow seed in fall or set transplants in spring; reseeds.' },
  { id: 'coneflower', name: 'Purple Coneflower', botanical: 'Echinacea purpurea',
    type: 'perennial', native: true, sun: 'part shade', water: 'medium',
    plantMonths: [10,11,2,3,4], bloomMonths: [4,5,6,7,8,9],
    establishDays: 45, heightFt: 3, spacingFt: 1.5, color: '#4f7a3f', bloom: '#c05a9e',
    notes: 'Goldfinches eat the seed heads — leave them standing.' },
  { id: 'indianblanket', name: 'Indian Blanket', botanical: 'Gaillardia pulchella',
    type: 'perennial', native: true, sun: 'full sun', water: 'low',
    plantMonths: [10,11], bloomMonths: [4,5,6,7,8],
    establishDays: 30, heightFt: 1.5, spacingFt: 1, color: '#6f8a3e', bloom: '#e8552c',
    notes: 'Wildflower — broadcast seed in fall onto bare soil, then leave it alone.' },
  { id: 'winecup', name: 'Winecup', botanical: 'Callirhoe involucrata',
    type: 'groundcover', native: true, sun: 'full sun', water: 'low',
    plantMonths: [10,11,2,3], bloomMonths: [3,4,5,6],
    establishDays: 45, heightFt: 0.5, spacingFt: 2, color: '#5e8248', bloom: '#a3286b',
    notes: 'Sprawling magenta cups in spring; goes dormant in deep summer.' },
  { id: 'mealysage', name: 'Mealy Blue Sage', botanical: 'Salvia farinacea',
    type: 'perennial', native: true, sun: 'full sun', water: 'low',
    plantMonths: [3,4,9,10], bloomMonths: [3,4,5,6,7,8,9,10,11],
    establishDays: 30, heightFt: 2, spacingFt: 1.5, color: '#5c8050', bloom: '#5a5fd0',
    notes: 'Long blue spikes; bees love it; shrugs off heat.' },
  { id: 'cardinalflower', name: 'Cardinal Flower', botanical: 'Lobelia cardinalis',
    type: 'perennial', native: true, sun: 'part shade', water: 'high',
    plantMonths: [9,10,2,3], bloomMonths: [8,9,10],
    establishDays: 45, heightFt: 3, spacingFt: 1, color: '#3f7040', bloom: '#d81f2a',
    notes: 'For the soggy low spot every Houston yard has. Late-summer red spires.' },
  { id: 'aquaticmilkweed', name: 'Aquatic Milkweed', botanical: 'Asclepias perennis',
    type: 'perennial', native: true, sun: 'part shade', water: 'high',
    plantMonths: [9,10,3,4], bloomMonths: [5,6,7,8,9],
    establishDays: 60, heightFt: 2, spacingFt: 1, color: '#4a7d45', bloom: '#e8e4e0',
    notes: 'Monarch host that actually likes Gulf Coast wet clay (unlike tropical milkweed — skip that one).' },
  { id: 'frogfruit', name: 'Frogfruit', botanical: 'Phyla nodiflora',
    type: 'groundcover', native: true, sun: 'part shade', water: 'low',
    plantMonths: [3,4,5,9,10], bloomMonths: [5,6,7,8,9,10],
    establishDays: 30, heightFt: 0.3, spacingFt: 2, color: '#5f8a52', bloom: '#efeada',
    notes: 'Native lawn alternative; mowable, walkable, tiny pollinator flowers.' },
  { id: 'seaoats', name: 'Inland Sea Oats', botanical: 'Chasmanthium latifolium',
    type: 'grass', native: true, sun: 'shade', water: 'medium',
    plantMonths: [9,10,11,2,3], bloomMonths: [8,9,10],
    establishDays: 60, heightFt: 3, spacingFt: 2, color: '#6b8f4e', bloom: '#c9b46a',
    notes: 'Graceful seed heads in dry shade under trees, where nothing else grows.' },
  { id: 'littlebluestem', name: 'Little Bluestem', botanical: 'Schizachyrium scoparium',
    type: 'grass', native: true, sun: 'full sun', water: 'low',
    plantMonths: [10,11,2,3], bloomMonths: [9,10,11],
    establishDays: 90, heightFt: 3, spacingFt: 2, color: '#7d9068', bloom: '#b0785a',
    notes: 'Prairie backbone grass; copper-red all winter.' },
  { id: 'beautyberry', name: 'American Beautyberry', botanical: 'Callicarpa americana',
    type: 'shrub', native: true, sun: 'part shade', water: 'medium',
    plantMonths: [10,11,12,1,2], bloomMonths: [9,10,11],
    establishDays: 90, heightFt: 5, spacingFt: 5, color: '#4d7a3a', bloom: '#b13fc4',
    notes: 'Neon-purple berry clusters in fall; mockingbirds strip them by December.' },
  { id: 'yaupon', name: 'Yaupon Holly', botanical: 'Ilex vomitoria',
    type: 'shrub', native: true, sun: 'part shade', water: 'low',
    plantMonths: [10,11,12,1,2], bloomMonths: [11,12,1],
    establishDays: 120, heightFt: 12, spacingFt: 6, color: '#2f5c33', bloom: '#d84040',
    notes: 'Evergreen screen, red winter berries, and the only native caffeine plant in North America.' },
  { id: 'coralhoneysuckle', name: 'Coral Honeysuckle', botanical: 'Lonicera sempervirens',
    type: 'vine', native: true, sun: 'part shade', water: 'medium',
    plantMonths: [10,11,2,3], bloomMonths: [3,4,5,6,7,8,9,10],
    establishDays: 60, heightFt: 10, spacingFt: 3, color: '#456e3a', bloom: '#e05545',
    notes: 'Well-behaved native vine for a fence — NOT the invasive Japanese honeysuckle.' },
  { id: 'passionvine', name: 'Purple Passionflower', botanical: 'Passiflora incarnata',
    type: 'vine', native: true, sun: 'full sun', water: 'medium',
    plantMonths: [3,4,5,9], bloomMonths: [5,6,7,8,9],
    establishDays: 45, heightFt: 12, spacingFt: 4, color: '#4c7d3c', bloom: '#8a6bc0',
    notes: 'Host plant for gulf fritillaries — expect (welcome) caterpillars.' },
  { id: 'buttonbush', name: 'Buttonbush', botanical: 'Cephalanthus occidentalis',
    type: 'shrub', native: true, sun: 'part shade', water: 'high',
    plantMonths: [10,11,12,1,2], bloomMonths: [6,7,8],
    establishDays: 90, heightFt: 8, spacingFt: 6, color: '#40703c', bloom: '#efe7d8',
    notes: 'Sputnik-shaped blooms; for the spot that floods when it rains.' },

  // ---------- Native trees (plant Oct–Feb) ----------
  { id: 'liveoak', name: 'Live Oak', botanical: 'Quercus virginiana',
    type: 'tree', native: true, sun: 'full sun', water: 'low',
    plantMonths: [10,11,12,1,2], bloomMonths: [],
    establishDays: 365, heightFt: 45, spacingFt: 30, color: '#2e5b2a', bloom: '#2e5b2a',
    notes: 'The Houston shade tree. Plant once, benefit for a century.' },
  { id: 'pecan', name: 'Pecan', botanical: 'Carya illinoinensis',
    type: 'tree', native: true, sun: 'full sun', water: 'medium',
    plantMonths: [12,1,2], bloomMonths: [],
    establishDays: 365, heightFt: 70, spacingFt: 40, color: '#3f6b33', bloom: '#3f6b33',
    notes: 'State tree of Texas; bare-root plant in winter.' },
  { id: 'txredbud', name: 'Texas Redbud', botanical: 'Cercis canadensis var. texensis',
    type: 'tree', native: true, sun: 'part shade', water: 'low',
    plantMonths: [10,11,12,1,2], bloomMonths: [2,3],
    establishDays: 180, heightFt: 20, spacingFt: 15, color: '#4a7238', bloom: '#d055a0',
    notes: 'Purple-pink bloom before the leaves in February. Great understory tree.' },
  { id: 'mexicanplum', name: 'Mexican Plum', botanical: 'Prunus mexicana',
    type: 'tree', native: true, sun: 'part shade', water: 'low',
    plantMonths: [10,11,12,1,2], bloomMonths: [2,3],
    establishDays: 180, heightFt: 20, spacingFt: 15, color: '#48703a', bloom: '#f2ecdf',
    notes: 'Fragrant white spring bloom, small edible plums, feeds everything.' },
  { id: 'possumhaw', name: 'Possumhaw Holly', botanical: 'Ilex decidua',
    type: 'tree', native: true, sun: 'part shade', water: 'medium',
    plantMonths: [10,11,12,1,2], bloomMonths: [12,1,2],
    establishDays: 180, heightFt: 15, spacingFt: 10, color: '#4f7742', bloom: '#e04a30',
    notes: 'Drops its leaves to show off thousands of red berries all winter.' },

  // ---------- Edibles (Harris County fall/spring calendar) ----------
  { id: 'falltomato', name: 'Tomato (fall crop)', botanical: 'Solanum lycopersicum',
    type: 'edible', native: false, sun: 'full sun', water: 'high',
    plantMonths: [7,8,2,3], bloomMonths: [9,10,11,4,5],
    establishDays: 30, heightFt: 4, spacingFt: 2, color: '#4e8a3a', bloom: '#e23b2e',
    notes: 'Set transplants NOW (late July–Aug) for harvest before first frost (~mid-Dec).' },
  { id: 'pepper', name: 'Pepper', botanical: 'Capsicum annuum',
    type: 'edible', native: false, sun: 'full sun', water: 'medium',
    plantMonths: [7,8,3,4], bloomMonths: [9,10,11,5,6],
    establishDays: 30, heightFt: 2.5, spacingFt: 1.5, color: '#47823c', bloom: '#3fae4a',
    notes: 'Fall peppers outproduce spring ones here — plant by end of August.' },
  { id: 'bushbeans', name: 'Bush Beans', botanical: 'Phaseolus vulgaris',
    type: 'edible', native: false, sun: 'full sun', water: 'medium',
    plantMonths: [8,9,3,4], bloomMonths: [9,10,4,5],
    establishDays: 14, heightFt: 1.5, spacingFt: 0.5, color: '#4f8f3f', bloom: '#7ec850',
    notes: 'Direct-sow; 50–60 days to harvest, so late August works.' },
  { id: 'cucumber', name: 'Cucumber', botanical: 'Cucumis sativus',
    type: 'edible', native: false, sun: 'full sun', water: 'high',
    plantMonths: [8,3,4], bloomMonths: [9,10,4,5],
    establishDays: 14, heightFt: 1, spacingFt: 1.5, color: '#3f8a45', bloom: '#e8c832',
    notes: 'Fall sowing window closes early September.' },
  { id: 'squash', name: 'Summer Squash', botanical: 'Cucurbita pepo',
    type: 'edible', native: false, sun: 'full sun', water: 'high',
    plantMonths: [8,3,4], bloomMonths: [9,10,4,5],
    establishDays: 14, heightFt: 1.5, spacingFt: 3, color: '#4a8a38', bloom: '#f0b429',
    notes: 'Fall crop dodges most vine-borer pressure.' },
  { id: 'broccoli', name: 'Broccoli', botanical: 'Brassica oleracea var. italica',
    type: 'edible', native: false, sun: 'full sun', water: 'medium',
    plantMonths: [9,10], bloomMonths: [11,12,1],
    establishDays: 21, heightFt: 2, spacingFt: 1.5, color: '#3d7a44', bloom: '#5da154',
    notes: 'Transplants mid-Sep through October; sweetens after cool nights.' },
  { id: 'kale', name: 'Kale / Collards', botanical: 'Brassica oleracea',
    type: 'edible', native: false, sun: 'part shade', water: 'medium',
    plantMonths: [9,10,11], bloomMonths: [],
    establishDays: 21, heightFt: 2, spacingFt: 1, color: '#39704a', bloom: '#39704a',
    notes: 'Harvest leaf-by-leaf all winter; frost improves flavor.' },
  { id: 'lettuce', name: 'Lettuce', botanical: 'Lactuca sativa',
    type: 'edible', native: false, sun: 'part shade', water: 'medium',
    plantMonths: [9,10,11,12,1,2], bloomMonths: [],
    establishDays: 14, heightFt: 0.8, spacingFt: 0.7, color: '#69a648', bloom: '#69a648',
    notes: 'Succession-sow every 3 weeks from late September.' },
  { id: 'carrot', name: 'Carrot', botanical: 'Daucus carota subsp. sativus',
    type: 'edible', native: false, sun: 'full sun', water: 'medium',
    plantMonths: [9,10,11,12,1,2], bloomMonths: [],
    establishDays: 21, heightFt: 0.8, spacingFt: 0.3, color: '#57904a', bloom: '#57904a',
    notes: 'Needs loose soil — in this clay, grow in a raised/amended bed.' },
  { id: 'radish', name: 'Radish', botanical: 'Raphanus sativus',
    type: 'edible', native: false, sun: 'full sun', water: 'medium',
    plantMonths: [9,10,11,12,1,2,3], bloomMonths: [],
    establishDays: 7, heightFt: 0.5, spacingFt: 0.3, color: '#4f8a4f', bloom: '#4f8a4f',
    notes: '25 days seed-to-table; the instant-gratification crop.' },
  { id: 'spinach', name: 'Spinach', botanical: 'Spinacia oleracea',
    type: 'edible', native: false, sun: 'part shade', water: 'medium',
    plantMonths: [10,11,12,1], bloomMonths: [],
    establishDays: 14, heightFt: 0.6, spacingFt: 0.5, color: '#356e3d', bloom: '#356e3d',
    notes: 'Wait for soil to cool (October) or seed won\'t germinate.' },
  { id: 'garlic', name: 'Garlic', botanical: 'Allium sativum',
    type: 'edible', native: false, sun: 'full sun', water: 'low',
    plantMonths: [10,11], bloomMonths: [],
    establishDays: 30, heightFt: 1.5, spacingFt: 0.5, color: '#5e9455', bloom: '#5e9455',
    notes: 'Softneck varieties only in 9b; plant cloves Oct–Nov, harvest May.' },
  { id: 'cilantro', name: 'Cilantro', botanical: 'Coriandrum sativum',
    type: 'edible', native: false, sun: 'part shade', water: 'medium',
    plantMonths: [9,10,11,12,1,2], bloomMonths: [3,4],
    establishDays: 14, heightFt: 1, spacingFt: 0.5, color: '#4c8c44', bloom: '#eae6d4',
    notes: 'A winter herb in Houston — bolts instantly after March.' },
  { id: 'basil', name: 'Basil', botanical: 'Ocimum basilicum',
    type: 'edible', native: false, sun: 'full sun', water: 'medium',
    plantMonths: [3,4,5,6,7,8], bloomMonths: [6,7,8,9],
    establishDays: 14, heightFt: 1.5, spacingFt: 1, color: '#3f8f3f', bloom: '#e8d8ec',
    notes: 'Loves the heat; dies at first frost — pesto everything in November.' },
];

window.PLANT_BY_ID = Object.fromEntries(window.PLANTS.map(p => [p.id, p]));
